#!/usr/bin/env bash

# Tell build process to exit if there are any errors.
set -oe pipefail

TYPE="signed"
IMAGE="ghcr.io/colbywanshinobi/blueox-os:latest"

if [[ -n ${1} ]]; then
  TYPE=$(echo "${1}" | tr '[:upper:]' '[:lower:]')
fi

if [[ -n ${2} ]]; then
  IMAGE=${2}
fi

usage() {
  echo "$0 TYPE IMAGE"
  echo "      TYPE  - <signed/unsigned> Update to a signed or unsigned image. DEFAULT = signed"
  echo "      IMAGE   - the location of the image to be updated to. Default is blueox:latest"
}

if [[ ${TYPE} == 'signed' ]]; then
    echo "Perform update to SIGNED image: ${IMAGE} ? [y/n]"
    read user_input
    if [ "$user_input" == "y" ]; then
        sudo rpm-ostree rebase ostree-image-signed:docker://${IMAGE}
        echo "You must reboot for this change to take effect..."
    else
        echo "Operation canceled."
        exit 0
    fi
elif [[ ${TYPE} == 'unsigned' ]]; then
    echo "Perform update to UNSIGNED image: ${IMAGE} ? [y/n]"
    read user_input
    if [ "$user_input" == "y" ]; then
        sudo rpm-ostree rebase ostree-unverified-registry:${IMAGE}
        echo "You must reboot for this change to take effect..."
    else
        echo "Operation canceled."
        exit 0
    fi
else 
    usage
fi


