on:
  workflow_dispatch:
    inputs:
      fedora-version:
        description: 'Fedora Version'
        required: true
        default: '40'
  repository_dispatch:
    types: [trigger-release]
name: release-blueox-os
jobs:
  build-iso:
    name: Generate and Release ISOs
    runs-on: ubuntu-latest
    container:
      image: fedora:${{ github.event.inputs.fedora_version }}
      options: --privileged
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - name: Generate ISO
        uses: ublue-os/isogenerator@v2.2.0
        id: isogenerator
        with:
          image-name: ${{ github.event.repository.name }}
          installer-repo: releases
          installer-major-version: ${{ github.event.inputs.fedora_version }}
          boot-menu-path: boot_menu.yml
      - name: Install GitHub CLI in Runner
        run: |
          sudo dnf install 'dnf-command(config-manager)' -y
          sudo dnf config-manager --add-repo https://cli.github.com/packages/rpm/gh-cli.repo
          sudo dnf install gh -y
      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date +'%Y%m%d')"
      - name: Create Release
        env:
          GITHUB_TOKEN: ${{ github.token }}
        run: |
          gh release create \
            ${{ github.event.inputs.fedora_version }}-${{ steps.date.outputs.date }} \
            --target main \
            --repo ${{ github.repository_owner }}/${{ github.event.repository.name }} \
            --notes ${{ github.event.inputs.fedora_version }}-${{ steps.date.outputs.date }} \
            || true

      - name: Upload ISO
        env:
          GITHUB_TOKEN: ${{ github.token }}
        run: |
          gh release upload \
            ${{ github.event.inputs.fedora_version }}-${{ steps.date.outputs.date }} \
            ./${{ steps.isogenerator.outputs.iso-path }} \
            --repo ${{ github.repository_owner }}/${{ github.event.repository.name }} \
            --clobber

      - name: Upload SHA256SUM
        env:
          GITHUB_TOKEN: ${{ github.token }}
        run: |
          gh release upload \
            ${{ github.event.inputs.fedora_version }}-${{ steps.date.outputs.date }} \
            ./${{ steps.isogenerator.outputs.sha256sum-path }} \
            --repo ${{ github.repository_owner }}/${{ github.event.repository.name }} \
            --clobber

      - name: Trigger Release Workflow
        if: success() && github.event_name != 'pull_request'
        run: |
          curl -X POST \
          -H "Accept: application/vnd.github.v3+json" \
          -H "Authorization: token ${{ github.token }}" \
          https://api.github.com/repos/${{ github.repository }}/dispatches \
          -d '{"event_type": "trigger-release"}'
